name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm i

    - name: Run tests
      run: npm run coverage
    
    - name: "Upload coverage report"
      run: |
        ci_env=`curl -s https://codecov.io/env`
        npm install codecov -g
        codecov -t 104f34bd-e77f-4f49-90ee-78e08168ec38
